export const fieldLabels: Record<string, string> = {
  tipoProcesso: "Tipo de Processo",
  numeroProcesso: "Nº Processo",
  dataDistribuicao: "Data Distribuição",
  vara: "Vara",
  comarca: "Comarca",
  foro: "Foro",
  valorCausa: "Valor da Causa",
  resumoFatos: "Resumo dos Fatos",
  autor: "Autor",
  reu: "Réu",
  cpfAutor: "CPF Autor",
  cnpjAutor: "CNPJ Autor",
  cpfReu: "CPF Réu",
  cnpjReu: "CNPJ Réu",
  advogadoAutor: "Advogado Autor",
  advogadoReu: "Advogado Réu",
  numeroVoo: "Nº Voo",
  codigoIATA: "Código IATA",
  origem: "Origem",
  destino: "Destino",
  dataOcorrencia: "Data Ocorrência",
  tipoOcorrencia: "Tipo de Ocorrência",
  tipoDano: "Tipo de Dano",
};
